### ISSUE TITLE
cpp_url_fetch doesn't work with SDK v22.12.1

### ISSUE THREAD

**Issue by cpswan** [edjx/edjurl#2]
Following the instructions for [prerequisites](https://docs.edjx.net/docs/latest/serverless/create_cpp_function.html#_prerequisites) installed the latest v22.12.1 SDK.

When I then ran `make all` that failed, because the Makefile presently expects v21.11.1:

```makefile
# SDK versions that will be used for compilation
# (CHANGE THE VERSION NUMBERS IF NEEDED)
WASI_SDK_VERSION := 12.0
EDJX_CPP_SDK_VERSION := v21.11.1-wasi-12
```

I modified `EDJX_CPP_SDK_VERSION`:

```makefile
EDJX_CPP_SDK_VERSION := v22.12.1-wasi-12
```

But that results in an error from `make all`:

```
mkdir -p bin/
mkdir -p build/
/home/chris/edjx/wasi-sdk-12.0/bin/clang++ -MD -MP --target=wasm32-wasi -std=c++17 --sysroot=/home/chris/edjx/wasi-sdk-12.0/share/wasi-sysroot/ -Wall -Werror -O2 -fno-exceptions -static -I/home/chris/edjx/edjx-cpp-sdk-v22.12.1-wasi-12/include -c -o build//serverless_function.o src//serverless_function.cpp
/home/chris/edjx/wasi-sdk-12.0/bin/clang++ -MD -MP --target=wasm32-wasi -std=c++17 --sysroot=/home/chris/edjx/wasi-sdk-12.0/share/wasi-sysroot/ -Wall -Werror -O2 -fno-exceptions -static -I/home/chris/edjx/edjx-cpp-sdk-v22.12.1-wasi-12/include -c -o build//lib.o src//lib.cpp
src//lib.cpp:22:51: error: too many arguments to function call, expected single argument 'result', have 2 arguments
    HttpError err = HttpRequest::from_client(req, true);
                    ~~~~~~~~~~~~~~~~~~~~~~~~      ^~~~
/home/chris/edjx/edjx-cpp-sdk-v22.12.1-wasi-12/include/edjx/request.hpp:60:39: note: 'from_client' declared here
        static edjx::error::HttpError from_client(HttpRequest & result);
                                      ^
1 error generated.
make: *** [Makefile:69: build//lib.o] Error 1
```

Installing the v21.11.1 SDK and reverting the Makefile got me a working build. But I'd expect that this example would keep track of any breaking changes in the SDK (or alternatively that the linked prerequisites installs a pinned version of the SDK that matches the Makefile and that's known to work).
